name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --no-build --output ./output

    - name: Zip Files
      run: Compress-Archive -Path ./output/*  mgsscripttools.zip

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: mgsscripttools.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}